version: "3.9"
services:
  starwars:
    image: inigohub/starwars:0.1.5
    ports: 
      - 81:80 # Remove this to disallow direct access to playground
    
  sidecar:
    image: inigohub/sidecar:0.1.8
    ports: 
      - 80:80
    environment:
      SIDECAR_LISTEN_PORT: 80
      SIDECAR_EGRESS_URL: http://starwars
      SIDECAR_GRAPHQL_ROUTE: /query
      SIDECAR_INGEST_URL: https://prod.inigolabs.com/ingest/query
      SIDECAR_SERVICE_URL: https://prod.inigolabs.com/service/query
    env_file: service.token


