version: "3.9"
services:
  starwars:
    image: inigohub/starwars:0.1.5
    ports:
      - 81:80 # Remove this to disallow direct access to playground
  sidecar:
    image: inigohub/sidecar:v0.9.0
    ports:
      - 80:80
    environment:
      INIGO_EGRESS_URL: http://starwars:80/query
      INIGO_GRAPHQL_ROUTE: /query
      INIGO_QUERYDATABATCH_MAX_TIME: 5s
      INIGO_QUERYDATABATCH_MAX_COUNT: "50"

    env_file: service.token
