name: starwars
kind: Service
spec:
  path_user_role: jwt.user_role
  path_user_name: jwt.user_name
  polling_interval_schema: 300
  polling_interval_profile: 5
  validation:
    alias_name: "^[a-zA-Z0-9_-]+$"
    directive_name: "^[a-zA-Z0-9_-]+$"
    operation_name: "^[a-zA-Z0-9_-]+$"
    arguments:
      String: "^[a-zA-Z0-9_-]+$"
  profiles:
  - name: guest
    max_depth:  3
    max_height: 10
    max_directives: 5
    require_operation_name: true
    max_request_size_bytes: 512000
    max_response_size_bytes: 2048000
    access:
      config: access/guest.inigo
      introspection: FULL
    rate_limit:
      mode: static
      credits_per_minute: 1000
      calls_per_minute: 100
  - name: admin
    max_depth: 5
    max_height: 100
    max_operations: 1
    max_request_size_bytes: 51200
    max_response_size_bytes: 2048000
    rate_limit:
      mode: static
      credits_per_minute: 1000
    access:
      config: access/admin.inigo
      introspection: FULL
  - name: user
    max_depth: 5
    max_height: 100
    max_operations: 1
    max_request_size_bytes: 512000
    max_response_size_bytes: 2048000
    rate_limit:
      mode: static
      credits_per_minute: 1000
    access:
      config: access/user.inigo
      introspection: BLOCK
  - name: super
    max_depth: 5
    access:
      introspection: FULL
