kind: Service
name: starwars
spec:
  path_user_role: jwt.user_role
  path_user_name: jwt.user_name
  polling_interval_schema: 20
  polling_interval_profile: 30
  validation:
    alias_name: "^[a-zA-Z0-9_-]+$"
    directive_name: "^[a-zA-Z0-9_-]+$"
    operation_name: "^[a-zA-Z0-9_-]+$"
    arguments:
      String: "^[a-zA-Z0-9_-]+$"
  profiles:
    - name: guest
      max_depth: 10
      max_height: 10
      max_directives: 5
      require_operation_name: true
      max_request_size_bytes: 512000
      max_response_size_bytes: 2048000
      rate_limit:
        mode: static
        header_output: false
        extension_output: false
        calls_per_minute: 100
        calls_per_hour: 1000
        credits_per_minute: 1000
        credits_per_hour: 10000
      access:
        config_files:
          - access/guest.inigo
        introspection: FULL
      pii:
        - CreditCard
        - SSN
    - name: admin
      max_depth: 5
      max_height: 100
      max_request_size_bytes: 512000
      max_response_size_bytes: 2048000
      rate_limit:
        mode: static
        calls_per_minute: 10
        credits_per_minute: 1000
      access:
        config_files:
          - access/admin.inigo
    - name: user
      max_depth: 5
      max_height: 100
      max_request_size_bytes: 512000
      max_response_size_bytes: 2048000
      rate_limit:
        mode: static
        calls_per_minute: 10
        credits_per_minute: 1000
      access:
        config_files:
          - access/user.inigo
    - name: super
      max_depth: 5