version: "3.9"
services:
  dvga:
    image: dolevf/dvga:2.0.0
    environment:
      WEB_HOST: 0.0.0.0
      WEB_PORT: 5013
  sidecar:
    image: inigohub/sidecar:0.5.0
    ports:
      - 80:80
    environment:
      SIDECAR_LISTEN_PORT: "80"
      SIDECAR_EGRESS_URL: http://dvga:5013
      SIDECAR_GRAPHQL_ROUTE: /graphql
    env_file: service.token
